<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>PjSip.Net.Native.iOS</PackageId>
    <Description>Native PJSIP pjsua2 binaries for iOS arm64</Description>
    <PackageTags>pjsip;native;ios;arm64</PackageTags>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <NoDefaultExcludes>true</NoDefaultExcludes>
    <IncludeSymbols>false</IncludeSymbols>
    <NoWarn>$(NoWarn);NU5128</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\..\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="runtimes\ios-arm64\native\**" PackagePath="runtimes/ios-arm64/native" />
    <None Include="build\**" Pack="true" PackagePath="build" />
    <None Include="buildTransitive\**" Pack="true" PackagePath="buildTransitive" />
  </ItemGroup>

</Project>
