<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>PjSip.Net.Interop</PackageId>
    <Description>Low-level SWIG-generated interop layer for PJSIP pjsua2 library</Description>
    <PackageTags>pjsip;sip;voip;interop;pjsua2</PackageTags>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);CA2255</NoWarn>
    <LangVersion>default</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\..\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PjSip.Net.Native.Win64\PjSip.Net.Native.Win64.csproj" />
    <ProjectReference Include="..\PjSip.Net.Native.MacOS\PjSip.Net.Native.MacOS.csproj" />
    <ProjectReference Include="..\PjSip.Net.Native.Android\PjSip.Net.Native.Android.csproj" />
    <ProjectReference Include="..\PjSip.Net.Native.iOS\PjSip.Net.Native.iOS.csproj" />
  </ItemGroup>

</Project>
